FROM ubuntu:18.04

RUN apt update
RUN apt-get upgrade -y
RUN apt install curl -y
RUN apt install tesseract-ocr -y
RUN apt install tesseract-ocr-spa
RUN apt install software-properties-common -y
RUN curl -sL https://deb.nodesource.com/setup_15.x | bash -
RUN apt-get install -y nodejs

WORKDIR /home/app

COPY [".env", "package.json", "package-lock.json", "/home/app/"]

RUN cd /home/app && npm ci
CMD ["npm", "run", "docker:container:dev"]
