FROM node:current-slim

RUN apt update
RUN apt install tesseract-ocr -y
RUN apt install tesseract-ocr-spa
RUN mkdir /home/app

WORKDIR /home/app

COPY [".env", "package.json", "package-lock.json", "/home/app/"]

RUN cd /home/app && npm ci
CMD ["npm", "run", "docker:container:dev"]
