FROM node:current-slim

RUN apt update
RUN apt install tesseract-ocr -y
RUN mkdir /home/app

WORKDIR /home/app

COPY app /home/app/app
COPY [".env", "tsconfig.json", "package.json", "package-lock.json", "/home/app/"]

RUN cd /home/app && npm ci
RUN npm run build
RUN rm -r app

CMD ["node", "built/index.js"]
